### ISSUE TITLE
Github releases?

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-sql#6]
For non Java programmers figuring out that there's a release does not come easy.
Perhaps do github tags/releases too?

Market has releases: 
https://market.enonic.com/vendors/enonic/com.enonic.lib.sql

Lib-sql in artifactory:
http://repo.enonic.com/webapp/#/search/quick/eyJzZWFyY2giOiJxdWljayIsInF1ZXJ5IjoibGliLXNxbCJ9

**Comment by alansemenov** [comment]
Started tagging releases from 1.0.0
