### ISSUE TITLE
connect url file path is relative to where you started Enonic XP server from?

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-sql#7]
For me it looks like the connect url file path is relative to where you started Enonic XP server from.
Perhaps this fact should be documented somewhere?

**Comment by sigdestad** [comment]
What do you mean, like the SQL connection string varies on XP deployment location?

**Comment by ComLock** [comment]
It seems. The SQL connection string varies on where you ran the server.sh
command from.

**Comment by srs** [comment]
Yes, if you use a connection url that uses a file path it will be up to the driver to sort of the location. Some drivers use the current working directory. And that depends on what directory you are actually standing in. It could be that Enonic XP could set the working directory to some place, but that's an improvement to Enonic XP and not `lib-sql`.
